"""
Phase 5: Sequence Step Executor Engine.
Evaluates DAG state machines, checks rate limits, executes actions via Voyager/Playwright,
and transitions leads to subsequent steps with delay timers.
"""
import logging
from datetime import datetime, timedelta, timezone
from typing import Any
from motor.motor_asyncio import AsyncIOMotorDatabase

from outreach.models import LeadExecutionState, SequenceNodeType
from outreach.core.rate_limiter import OutboundRateLimiter
from outreach.core.proxy_manager import JITProxyManager
from outreach.core.dag_compiler import contains_ai_prompt_token, interpolate_template
from outreach.core.voice_cloner import VoiceCloner
from outreach.engine.voyager_client import VoyagerClient

logger = logging.getLogger(__name__)


class SequenceExecutor:
    """
    Executes a single step in a lead's outreach sequence.
    """

    @staticmethod
    async def execute_lead_step(lead_id: str, db: AsyncIOMotorDatabase) -> dict[str, Any]:
        lead = await db.outreach_leads.find_one({"id": lead_id})
        if not lead:
            return {"status": "lead_not_found"}

        if lead.get("execution_state") in (
            LeadExecutionState.FINISHED,
            LeadExecutionState.BOUNCED,
            LeadExecutionState.FAILED,
        ):
            return {"status": "terminal_state", "state": lead.get("execution_state")}
        if lead.get("execution_state") == LeadExecutionState.REPLIED and not lead.get("waiting_for_reply_at"):
            return {"status": "terminal_state", "state": lead.get("execution_state")}

        # 1. Fetch Campaign and verify active status
        campaign = await db.outreach_campaigns.find_one({"id": lead["campaign_id"], "is_deleted": {"$ne": True}})
        if not campaign or campaign.get("status") != "active":
            return {"status": "campaign_not_active"}

        # 2. Verify Working Hours
        schedule_data = campaign.get("schedule") or {}
        if not OutboundRateLimiter.is_within_working_hours(schedule_data):
            logger.info("Lead %s step skipped: currently outside working hours", lead_id)
            return {"status": "outside_working_hours"}

        # 3. Fetch Assigned Sender Account
        assigned_account_id = lead.get("assigned_account_id")
        if not assigned_account_id:
            return {"status": "no_account_assigned"}

        account = await db.outreach_accounts.find_one({"id": assigned_account_id})
        if not account or account.get("status") != "active":
            return {"status": "account_unavailable"}

        # 4. Fetch Sequence DAG
        sequence = await db.outreach_sequences.find_one({
            "campaign_id": lead["campaign_id"],
            "is_deleted": {"$ne": True},
        })
        if not sequence or "compiled_dag" not in sequence:
            return {"status": "sequence_not_configured"}

        compiled = sequence["compiled_dag"]
        nodes_lookup = compiled.get("nodes", {})
        root_node_ids = compiled.get("root_node_ids", [])

        # Determine current node
        curr_node_id = lead.get("current_node_id")
        if not curr_node_id:
            curr_node_id = root_node_ids[0] if root_node_ids else None

        if not curr_node_id or curr_node_id not in nodes_lookup:
            await db.outreach_leads.update_one(
                {"id": lead_id},
                {"$set": {"execution_state": LeadExecutionState.FINISHED}}
            )
            return {"status": "finished", "reason": "no_more_nodes"}

        node = nodes_lookup[curr_node_id]
        node_type = node.get("type")
        if contains_ai_prompt_token(node.get("config", {})):
            reason = "AI prompt tokens are not generated by the live campaign runner. Replace this step with finished message copy."
            await db.outreach_leads.update_one(
                {"id": lead_id},
                {"$set": {
                    "execution_state": LeadExecutionState.FAILED,
                    "failure_reason": reason,
                    "updated_at": datetime.now(timezone.utc),
                }}
            )
            return {"status": "action_failed", "action": node_type, "reason": reason}

        # 5. Initialize Voyager Client with proxy
        proxy_url = None
        if account.get("proxy"):
            proxy_url = JITProxyManager.format_proxy_url(account["proxy"])

        voyager = VoyagerClient(
            session_cookie_enc=account.get("session_cookie_enc", ""),
            jsession_id=account.get("jsession_id", ""),
            proxy_url=proxy_url,
        )

        # Connection and reply branches are conditions to wait for, not an
        # immediate check after sending. Keep the lead on this node until the
        # signal arrives or the seven-day branch timeout expires.
        waiting_field = "waiting_for_connection_at" if node_type in (SequenceNodeType.CONNECTION_REQUEST, SequenceNodeType.IF_CONNECTED) else (
            "waiting_for_reply_at" if node_type in (SequenceNodeType.SEND_MESSAGE, SequenceNodeType.VOICE_NOTE) else None
        )
        if waiting_field and lead.get(waiting_field):
            wait_started = lead[waiting_field]
            if isinstance(wait_started, str):
                try:
                    wait_started = datetime.fromisoformat(wait_started)
                except ValueError:
                    wait_started = datetime.now(timezone.utc)
            if wait_started.tzinfo is None:
                wait_started = wait_started.replace(tzinfo=timezone.utc)

            branch_signal = (
                await voyager.check_connection_status(lead.get("linkedin_urn") or lead["linkedin_url"])
                if node_type in (SequenceNodeType.CONNECTION_REQUEST, SequenceNodeType.IF_CONNECTED)
                else bool(lead.get("has_replied"))
            )
            branches = node.get("branches", {})
            try:
                default_timeout = 3 if node_type == SequenceNodeType.IF_CONNECTED else 7
                timeout_days = max(1, min(30, int(node.get("config", {}).get("timeout_days", default_timeout))))
            except (TypeError, ValueError):
                timeout_days = 7
            timeout_at = wait_started + timedelta(days=timeout_days)
            now = datetime.now(timezone.utc)
            if branch_signal or now >= timeout_at:
                next_node_id = branches.get("positive") if branch_signal else branches.get("negative")
                updates: dict[str, Any] = {
                    "current_node_id": next_node_id,
                    "execution_state": LeadExecutionState.QUEUED if next_node_id else LeadExecutionState.FINISHED,
                    "next_action_due_at": now,
                    "updated_at": now,
                }
                if node_type in (SequenceNodeType.CONNECTION_REQUEST, SequenceNodeType.IF_CONNECTED) and branch_signal:
                    updates["is_connected"] = True
                await db.outreach_leads.update_one(
                    {"id": lead_id},
                    {"$set": updates, "$unset": {waiting_field: ""}},
                )
                return {"status": "branch_advanced", "next_node_id": next_node_id, "condition_met": bool(branch_signal)}

            next_check = min(now + timedelta(hours=24), timeout_at)
            await db.outreach_leads.update_one(
                {"id": lead_id},
                {"$set": {
                    "execution_state": LeadExecutionState.WAITING_DELAY,
                    "next_action_due_at": next_check,
                    "updated_at": datetime.now(timezone.utc),
                }},
            )
            return {"status": "waiting_for_condition", "next_check_at": next_check.isoformat()}

        # 6. Execute Action with Rate Limiting
        action_name = node_type
        campaign_limits = campaign.get("limits") or {}
        action_result: dict[str, Any] | None = None

        if node_type == SequenceNodeType.VISIT_PROFILE:
            if not await OutboundRateLimiter.check_and_increment_daily_limit(account, "profile_visits", db, campaign_limits):
                return {"status": "rate_limited", "action": "profile_visits"}
            action_result = await voyager.visit_profile(lead["linkedin_url"])

        elif node_type == SequenceNodeType.CONNECTION_REQUEST:
            if not await OutboundRateLimiter.check_and_increment_daily_limit(account, "connection_invites", db, campaign_limits):
                return {"status": "rate_limited", "action": "connection_invites"}
            note_template = node.get("config", {}).get("note", "")
            custom_note = interpolate_template(note_template, lead) if note_template else ""
            action_result = await voyager.send_connection_invite(lead.get("linkedin_urn") or lead["linkedin_url"], custom_note)

        elif node_type == SequenceNodeType.SEND_MESSAGE:
            if not await OutboundRateLimiter.check_and_increment_daily_limit(account, "messages", db, campaign_limits):
                return {"status": "rate_limited", "action": "messages"}
            body_template = node.get("config", {}).get("body", "Hi {{first_name}}")
            msg_body = interpolate_template(body_template, lead)
            action_result = await voyager.send_direct_message(lead.get("linkedin_urn") or lead["linkedin_url"], msg_body)

        elif node_type == SequenceNodeType.LIKE_LAST_POST:
            if not await OutboundRateLimiter.check_and_increment_daily_limit(account, "post_likes", db, campaign_limits):
                return {"status": "rate_limited", "action": "post_likes"}
            action_config = node.get("config", {})
            action_result = await voyager.like_last_post(
                lead.get("linkedin_urn") or lead["linkedin_url"],
                max_age_days=action_config.get("max_post_age_days", 30),
            )
            no_post_found = (action_result.get("error") or "").lower().startswith(("no post found", "no recent post found"))
            if action_result.get("status") == "failed" and no_post_found and action_config.get("skip_if_no_posts", True):
                action_result = {"status": "skipped"}

        elif node_type == SequenceNodeType.VOICE_NOTE:
            if not await OutboundRateLimiter.check_and_increment_daily_limit(account, "voice_notes", db, campaign_limits):
                return {"status": "rate_limited", "action": "voice_notes"}

            # Resolve voice assigned to this account or workspace default
            voice = await db.outreach_voices.find_one({
                "workspace_id": account.get("workspace_id"),
                "assigned_account_ids": account.get("id"),
            })
            if not voice:
                voice = await db.outreach_voices.find_one({"workspace_id": account.get("workspace_id")})

            script_template = node.get("config", {}).get(
                "script", "Hey {{first_name}}, saw your work at {{company_name}} and wanted to send a quick voice note!"
            )
            voice_id = voice.get("elevenlabs_voice_id", "voice_mock_default") if voice else "voice_mock_default"

            cloner = VoiceCloner()
            audio_bytes = await cloner.synthesize_voice_note(
                voice_id=voice_id,
                template_text=script_template,
                lead=lead,
            )

            action_result = await voyager.send_voice_note(
                recipient_urn=lead.get("linkedin_urn") or lead["linkedin_url"],
                audio_bytes=audio_bytes,
                transcript=interpolate_template(script_template, lead),
            )
        elif node_type == SequenceNodeType.IF_CONNECTED:
            # Branch evaluation below performs the connection check; this node
            # intentionally has no outbound action and consumes no daily quota.
            action_result = {"status": "condition_checked"}

        else:
            reason = f"Unsupported sequence step: {node_type}"
            await db.outreach_leads.update_one(
                {"id": lead_id},
                {"$set": {
                    "execution_state": LeadExecutionState.FAILED,
                    "failure_reason": reason,
                    "updated_at": datetime.now(timezone.utc),
                }}
            )
            return {"status": "unsupported_action", "action": node_type}

        if not action_result or action_result.get("status") in {"failed", "error"}:
            reason = (action_result or {}).get("error") or f"LinkedIn action failed: {node_type}"
            await db.outreach_leads.update_one(
                {"id": lead_id},
                {"$set": {
                    "execution_state": LeadExecutionState.FAILED,
                    "failure_reason": reason,
                    "updated_at": datetime.now(timezone.utc),
                }}
            )
            return {"status": "action_failed", "action": node_type, "reason": reason}

        if node_type == SequenceNodeType.CONNECTION_REQUEST and node.get("branches"):
            waiting_since = datetime.now(timezone.utc)
            await db.outreach_leads.update_one(
                {"id": lead_id},
                {"$set": {
                    "waiting_for_connection_at": waiting_since,
                    "execution_state": LeadExecutionState.WAITING_DELAY,
                    "next_action_due_at": waiting_since + timedelta(hours=24),
                    "last_action_taken": action_name,
                    "last_action_at": waiting_since,
                    "updated_at": waiting_since,
                }},
            )
            return {"status": "success", "action": action_name, "waiting_for": "connection"}

        if node_type in (SequenceNodeType.SEND_MESSAGE, SequenceNodeType.VOICE_NOTE) and node.get("branches"):
            waiting_since = datetime.now(timezone.utc)
            await db.outreach_leads.update_one(
                {"id": lead_id},
                {"$set": {
                    "waiting_for_reply_at": waiting_since,
                    "execution_state": LeadExecutionState.WAITING_DELAY,
                    "next_action_due_at": waiting_since + timedelta(hours=24),
                    "last_action_taken": action_name,
                    "last_action_at": waiting_since,
                    "updated_at": waiting_since,
                }},
            )
            return {"status": "success", "action": action_name, "waiting_for": "reply"}

        # 7. Advance Lead State to Next Node in DAG
        next_node_id = None
        branches = node.get("branches", {})

        if branches.get("positive") or (node_type == SequenceNodeType.IF_CONNECTED and branches.get("negative")):
            if node_type in (SequenceNodeType.IF_CONNECTED,):
                branch_signal = await voyager.check_connection_status(lead.get("linkedin_urn") or lead["linkedin_url"])
            else:
                branch_signal = bool(lead.get("has_replied"))
            if branch_signal:
                next_node_id = branches["positive"]
                if node_type == SequenceNodeType.IF_CONNECTED:
                    await db.outreach_leads.update_one({"id": lead_id}, {"$set": {"is_connected": True}})
            else:
                if node_type == SequenceNodeType.IF_CONNECTED and not lead.get("waiting_for_connection_at"):
                    waiting_since = datetime.now(timezone.utc)
                    await db.outreach_leads.update_one(
                        {"id": lead_id},
                        {"$set": {
                            "waiting_for_connection_at": waiting_since,
                            "execution_state": LeadExecutionState.WAITING_DELAY,
                            "next_action_due_at": waiting_since + timedelta(hours=24),
                            "updated_at": waiting_since,
                        }},
                    )
                    return {"status": "waiting_for_condition", "next_check_at": (waiting_since + timedelta(hours=24)).isoformat()}
                next_node_id = branches.get("negative")
        else:
            next_node_id = node.get("next_default")

        # Determine delay for next step
        next_node = nodes_lookup.get(next_node_id) if next_node_id else None
        delay_hours = next_node.get("delay_hours", 24) if next_node else 0
        next_due = datetime.now(timezone.utc) + timedelta(hours=delay_hours)

        update_fields: dict[str, Any] = {
            "last_action_taken": action_name,
            "last_action_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        }

        if next_node_id:
            update_fields["current_node_id"] = next_node_id
            update_fields["execution_state"] = LeadExecutionState.WAITING_DELAY if delay_hours > 0 else LeadExecutionState.QUEUED
            update_fields["next_action_due_at"] = next_due
        else:
            update_fields["execution_state"] = LeadExecutionState.FINISHED

        await db.outreach_leads.update_one({"id": lead_id}, {"$set": update_fields})
        return {
            "status": "success",
            "action": action_name,
            "next_node_id": next_node_id,
            "next_action_due_at": next_due.isoformat(),
        }
