/**
 * Unravler Smart Bio - Theme, Tactile Card Physics, and Effect Utilities
 * Inspired by modern editorial design, high-converting physical UI, and Apple-grade craft.
 */

export const THEME_PRESETS = [
  // ── Reference Palette (Screenshot 1) ──
  {
    id: 'peach_blossom',
    name: 'Peach Blossom',
    subtitle: 'Warm coral rose & fresh white cards',
    background_type: 'gradient',
    background_color: '#FF6B8B',
    background_gradient: 'linear-gradient(135deg, #FF6B8B 0%, #FF8E53 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.4)',
    card_text_color: '#1C1C1E',
    button_radius: 'rounded-2xl',
    font_family: 'Manrope',
    accent_color: '#FF4B72',
    header_layout: 'centered',
  },
  {
    id: 'citrus',
    name: 'Citrus',
    subtitle: 'Zesty lime & fresh spring greenery',
    background_type: 'gradient',
    background_color: '#A8E063',
    background_gradient: 'linear-gradient(135deg, #A8E063 0%, #56AB2F 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.4)',
    card_text_color: '#1A2E05',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#4CAF50',
    header_layout: 'centered',
  },
  {
    id: 'creams',
    name: 'Creams',
    subtitle: 'Electric violet halo & pristine cards',
    background_type: 'gradient',
    background_color: '#7F00FF',
    background_gradient: 'linear-gradient(135deg, #7F00FF 0%, #E100FF 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.35)',
    card_text_color: '#2E1065',
    button_radius: 'rounded-2xl',
    font_family: 'Inter',
    accent_color: '#7C3AED',
    header_layout: 'centered',
  },
  {
    id: 'serpentine',
    name: 'Serpentine',
    subtitle: 'Muted sage teal & botanical calm',
    background_type: 'gradient',
    background_color: '#A8D5BA',
    background_gradient: 'linear-gradient(135deg, #C8E6C9 0%, #81C784 100%)',
    background_effect: 'none',
    text_color: '#134E4A',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(13, 148, 136, 0.15)',
    card_text_color: '#134E4A',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#0D9488',
    header_layout: 'centered',
  },
  {
    id: 'seashell',
    name: 'Seashell',
    subtitle: 'Ivory coastal sand & deep ocean blue',
    background_type: 'gradient',
    background_color: '#FFF5EB',
    background_gradient: 'linear-gradient(135deg, #FFF5EB 0%, #FDE2CA 100%)',
    background_effect: 'none',
    text_color: '#1C1917',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(0, 0, 0, 0.08)',
    card_text_color: '#1C1917',
    button_radius: 'rounded-2xl',
    font_family: 'Public Sans',
    accent_color: '#0284C7',
    header_layout: 'centered',
  },
  {
    id: 'apricot',
    name: 'Apricot',
    subtitle: 'Warm sun-ripened apricot glow',
    background_type: 'gradient',
    background_color: '#FDBA74',
    background_gradient: 'linear-gradient(135deg, #FFEDD5 0%, #FED7AA 100%)',
    background_effect: 'none',
    text_color: '#431407',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(234, 88, 12, 0.15)',
    card_text_color: '#431407',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#EA580C',
    header_layout: 'centered',
  },
  {
    id: 'aubergine',
    name: 'Aubergine',
    subtitle: 'Deep plum noir & velvet cards',
    background_type: 'dark',
    background_color: '#4A0E4E',
    background_gradient: 'linear-gradient(135deg, #4A0E4E 0%, #2A0845 100%)',
    background_effect: 'none',
    text_color: '#F3E8FF',
    card_style: 'glass_double_bezel',
    card_bg: 'rgba(255, 255, 255, 0.12)',
    card_border: 'rgba(255, 255, 255, 0.18)',
    card_text_color: '#F3E8FF',
    button_radius: 'rounded-2xl',
    font_family: 'Montserrat',
    accent_color: '#C084FC',
    header_layout: 'centered',
  },
  {
    id: 'seafoam',
    name: 'Seafoam',
    subtitle: 'Crisp mint seafoam & emerald accents',
    background_type: 'gradient',
    background_color: '#E0F2F1',
    background_gradient: 'linear-gradient(135deg, #E0F2F1 0%, #B2DFDB 100%)',
    background_effect: 'none',
    text_color: '#004D40',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(0, 137, 123, 0.15)',
    card_text_color: '#004D40',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#00897B',
    header_layout: 'centered',
  },
  {
    id: 'pistachio',
    name: 'Pistachio',
    subtitle: 'Organic herbal pistachio green',
    background_type: 'gradient',
    background_color: '#E8F5E9',
    background_gradient: 'linear-gradient(135deg, #E8F5E9 0%, #C8E6C9 100%)',
    background_effect: 'none',
    text_color: '#1B5E20',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(67, 160, 71, 0.15)',
    card_text_color: '#1B5E20',
    button_radius: 'rounded-2xl',
    font_family: 'Outfit',
    accent_color: '#43A047',
    header_layout: 'centered',
  },
  {
    id: 'mustard_seed',
    name: 'Mustard Seed',
    subtitle: 'Warm ochre vintage gold & olive depth',
    background_type: 'gradient',
    background_color: '#D4AF37',
    background_gradient: 'linear-gradient(135deg, #D4AF37 0%, #AA7C11 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FEF9C3',
    card_border: 'rgba(180, 83, 9, 0.2)',
    card_text_color: '#451A03',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#B45309',
    header_layout: 'centered',
  },
  {
    id: 'lilac',
    name: 'Lilac',
    subtitle: 'Soft dreamy lavender & royal purple',
    background_type: 'gradient',
    background_color: '#EDE9FE',
    background_gradient: 'linear-gradient(135deg, #EDE9FE 0%, #DDD6FE 100%)',
    background_effect: 'none',
    text_color: '#3B0764',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(139, 92, 246, 0.15)',
    card_text_color: '#3B0764',
    button_radius: 'rounded-2xl',
    font_family: 'Poppins',
    accent_color: '#8B5CF6',
    header_layout: 'centered',
  },
  {
    id: 'twilight',
    name: 'Twilight',
    subtitle: 'Midnight lavender dusk & frosted glass',
    background_type: 'dark',
    background_color: '#2E1065',
    background_gradient: 'linear-gradient(135deg, #2E1065 0%, #1E1B4B 100%)',
    background_effect: 'none',
    text_color: '#FAF5FF',
    card_style: 'glass_double_bezel',
    card_bg: 'rgba(255, 255, 255, 0.14)',
    card_border: 'rgba(255, 255, 255, 0.2)',
    card_text_color: '#FAF5FF',
    button_radius: 'rounded-2xl',
    font_family: 'Geist',
    accent_color: '#A78BFA',
    header_layout: 'centered',
  },
  {
    id: 'heather',
    name: 'Heather',
    subtitle: 'Muted dusty mauve & plum accents',
    background_type: 'gradient',
    background_color: '#F3E8FF',
    background_gradient: 'linear-gradient(135deg, #F3E8FF 0%, #E9D5FF 100%)',
    background_effect: 'none',
    text_color: '#581C87',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(147, 51, 234, 0.15)',
    card_text_color: '#581C87',
    button_radius: 'rounded-2xl',
    font_family: 'Inter',
    accent_color: '#9333EA',
    header_layout: 'centered',
  },
  {
    id: 'blue_mist',
    name: 'Blue Mist',
    subtitle: 'Serene morning sky & cobalt accents',
    background_type: 'gradient',
    background_color: '#E0F2FE',
    background_gradient: 'linear-gradient(135deg, #E0F2FE 0%, #BAE6FD 100%)',
    background_effect: 'none',
    text_color: '#0C4A6E',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(2, 132, 199, 0.15)',
    card_text_color: '#0C4A6E',
    button_radius: 'rounded-2xl',
    font_family: 'Public Sans',
    accent_color: '#0284C7',
    header_layout: 'centered',
  },
  {
    id: 'glacier',
    name: 'Glacier',
    subtitle: 'Pure arctic ice & crisp cyan reflections',
    background_type: 'gradient',
    background_color: '#F0F9FF',
    background_gradient: 'linear-gradient(135deg, #F0F9FF 0%, #E0F2FE 100%)',
    background_effect: 'none',
    text_color: '#0369A1',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(14, 165, 233, 0.15)',
    card_text_color: '#0369A1',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#0284C7',
    header_layout: 'centered',
  },
  {
    id: 'blush',
    name: 'Blush',
    subtitle: 'Sweet pastel rose & raspberry ink',
    background_type: 'gradient',
    background_color: '#FFE4E6',
    background_gradient: 'linear-gradient(135deg, #FFE4E6 0%, #FECDD3 100%)',
    background_effect: 'none',
    text_color: '#881337',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(225, 29, 72, 0.15)',
    card_text_color: '#881337',
    button_radius: 'rounded-2xl',
    font_family: 'Poppins',
    accent_color: '#E11D48',
    header_layout: 'centered',
  },
  {
    id: 'cornflower',
    name: 'Cornflower',
    subtitle: 'Royal sapphire blue & crisp paper',
    background_type: 'gradient',
    background_color: '#EEF2FF',
    background_gradient: 'linear-gradient(135deg, #EEF2FF 0%, #E0E7FF 100%)',
    background_effect: 'none',
    text_color: '#1E1B4B',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(79, 70, 229, 0.15)',
    card_text_color: '#1E1B4B',
    button_radius: 'rounded-2xl',
    font_family: 'Manrope',
    accent_color: '#4F46E5',
    header_layout: 'centered',
  },
  {
    id: 'meadow',
    name: 'Meadow',
    subtitle: 'Sunlit alpine pasture & dark clover',
    background_type: 'gradient',
    background_color: '#ECFDF5',
    background_gradient: 'linear-gradient(135deg, #ECFDF5 0%, #D1FAE5 100%)',
    background_effect: 'none',
    text_color: '#064E3B',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(5, 150, 105, 0.15)',
    card_text_color: '#064E3B',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#059669',
    header_layout: 'centered',
  },
  {
    id: 'rose',
    name: 'Rose',
    subtitle: 'Classic French garden petal pink',
    background_type: 'gradient',
    background_color: '#FFF1F2',
    background_gradient: 'linear-gradient(135deg, #FFF1F2 0%, #FFE4E6 100%)',
    background_effect: 'none',
    text_color: '#9F1239',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(244, 63, 94, 0.15)',
    card_text_color: '#9F1239',
    button_radius: 'rounded-2xl',
    font_family: 'Montserrat',
    accent_color: '#F43F5E',
    header_layout: 'centered',
  },
  {
    id: 'honey',
    name: 'Honey',
    subtitle: 'Rich organic wildflower honey & amber',
    background_type: 'gradient',
    background_color: '#FEF3C7',
    background_gradient: 'linear-gradient(135deg, #FEF3C7 0%, #FDE68A 100%)',
    background_effect: 'none',
    text_color: '#78350F',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(217, 119, 6, 0.15)',
    card_text_color: '#78350F',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#D97706',
    header_layout: 'centered',
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    subtitle: 'Sunbaked Mediterranean clay earthenware',
    background_type: 'gradient',
    background_color: '#FFEDD5',
    background_gradient: 'linear-gradient(135deg, #FFEDD5 0%, #FDBA74 100%)',
    background_effect: 'none',
    text_color: '#7C2D12',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(194, 65, 12, 0.15)',
    card_text_color: '#7C2D12',
    button_radius: 'rounded-2xl',
    font_family: 'Playfair Display',
    accent_color: '#C2410C',
    header_layout: 'centered',
  },
  {
    id: 'periwinkle',
    name: 'Periwinkle',
    subtitle: 'Ethereal pastel blue violet',
    background_type: 'gradient',
    background_color: '#E0E7FF',
    background_gradient: 'linear-gradient(135deg, #E0E7FF 0%, #C7D2FE 100%)',
    background_effect: 'none',
    text_color: '#1E1B4B',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(79, 70, 229, 0.15)',
    card_text_color: '#1E1B4B',
    button_radius: 'rounded-2xl',
    font_family: 'Inter',
    accent_color: '#4F46E5',
    header_layout: 'centered',
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    subtitle: 'Golden summer radiant bloom',
    background_type: 'gradient',
    background_color: '#FEF08A',
    background_gradient: 'linear-gradient(135deg, #FEF08A 0%, #FDE047 100%)',
    background_effect: 'none',
    text_color: '#713F12',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(202, 138, 4, 0.15)',
    card_text_color: '#713F12',
    button_radius: 'rounded-2xl',
    font_family: 'Outfit',
    accent_color: '#CA8A04',
    header_layout: 'centered',
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    subtitle: 'Juicy summer pink & vibrant cyan edge',
    background_type: 'gradient',
    background_color: '#FDA4AF',
    background_gradient: 'linear-gradient(135deg, #FDA4AF 0%, #FB7185 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.35)',
    card_text_color: '#881337',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#0D9488',
    header_layout: 'centered',
  },
  {
    id: 'spearmint',
    name: 'Spearmint',
    subtitle: 'Refreshing aqua breeze & emerald contrast',
    background_type: 'gradient',
    background_color: '#CCFBF1',
    background_gradient: 'linear-gradient(135deg, #CCFBF1 0%, #99F6E4 100%)',
    background_effect: 'none',
    text_color: '#115E59',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(13, 148, 136, 0.15)',
    card_text_color: '#115E59',
    button_radius: 'rounded-2xl',
    font_family: 'Public Sans',
    accent_color: '#0D9488',
    header_layout: 'centered',
  },
  {
    id: 'wisteria',
    name: 'Wisteria',
    subtitle: 'Hanging Japanese floral wisteria',
    background_type: 'gradient',
    background_color: '#E9D5FF',
    background_gradient: 'linear-gradient(135deg, #E9D5FF 0%, #D8B4FE 100%)',
    background_effect: 'none',
    text_color: '#581C87',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(147, 51, 234, 0.15)',
    card_text_color: '#581C87',
    button_radius: 'rounded-2xl',
    font_family: 'Poppins',
    accent_color: '#9333EA',
    header_layout: 'centered',
  },
  {
    id: 'sandstone',
    name: 'Sandstone',
    subtitle: 'Desert dunes & warm architectural linen',
    background_type: 'gradient',
    background_color: '#F5EBE0',
    background_gradient: 'linear-gradient(135deg, #F5EBE0 0%, #E6CCB2 100%)',
    background_effect: 'none',
    text_color: '#4A3525',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(156, 102, 68, 0.15)',
    card_text_color: '#4A3525',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#9C6644',
    header_layout: 'centered',
  },
  {
    id: 'hydrangea',
    name: 'Hydrangea',
    subtitle: 'Soft sky blue botanical clusters',
    background_type: 'gradient',
    background_color: '#DBEAFE',
    background_gradient: 'linear-gradient(135deg, #DBEAFE 0%, #BFDBFE 100%)',
    background_effect: 'none',
    text_color: '#1E3A8A',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(37, 99, 235, 0.15)',
    card_text_color: '#1E3A8A',
    button_radius: 'rounded-2xl',
    font_family: 'Inter',
    accent_color: '#2563EB',
    header_layout: 'centered',
  },
  {
    id: 'lemon_curd',
    name: 'Lemon Curd',
    subtitle: 'Pale chiffon citrus & strawberry garnish',
    background_type: 'gradient',
    background_color: '#FEF9C3',
    background_gradient: 'linear-gradient(135deg, #FEF9C3 0%, #FEF08A 100%)',
    background_effect: 'none',
    text_color: '#713F12',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(225, 29, 72, 0.15)',
    card_text_color: '#713F12',
    button_radius: 'rounded-2xl',
    font_family: 'Outfit',
    accent_color: '#E11D48',
    header_layout: 'centered',
  },
  {
    id: 'eucalyptus',
    name: 'Eucalyptus',
    subtitle: 'Silver dollar botanical & cedar shadow',
    background_type: 'gradient',
    background_color: '#D1FAE5',
    background_gradient: 'linear-gradient(135deg, #D1FAE5 0%, #A7F3D0 100%)',
    background_effect: 'none',
    text_color: '#064E3B',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(4, 120, 87, 0.15)',
    card_text_color: '#064E3B',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#047857',
    header_layout: 'centered',
  },
  {
    id: 'celery',
    name: 'Celery',
    subtitle: 'Fresh crisp garden stalk & chartreuse glow',
    background_type: 'gradient',
    background_color: '#ECFCCB',
    background_gradient: 'linear-gradient(135deg, #ECFCCB 0%, #D9F99D 100%)',
    background_effect: 'none',
    text_color: '#365314',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(101, 163, 13, 0.15)',
    card_text_color: '#365314',
    button_radius: 'rounded-2xl',
    font_family: 'Public Sans',
    accent_color: '#65A30D',
    header_layout: 'centered',
  },
  {
    id: 'iris',
    name: 'Iris',
    subtitle: 'Deep royal petal indigo & pastel wash',
    background_type: 'gradient',
    background_color: '#E0E7FF',
    background_gradient: 'linear-gradient(135deg, #E0E7FF 0%, #C7D2FE 100%)',
    background_effect: 'none',
    text_color: '#312E81',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(99, 102, 241, 0.15)',
    card_text_color: '#312E81',
    button_radius: 'rounded-2xl',
    font_family: 'Manrope',
    accent_color: '#6366F1',
    header_layout: 'centered',
  },
  {
    id: 'tulip',
    name: 'Tulip',
    subtitle: 'Dutch springtime crimson & warm parchment',
    background_type: 'gradient',
    background_color: '#FECDD3',
    background_gradient: 'linear-gradient(135deg, #FECDD3 0%, #FDA4AF 100%)',
    background_effect: 'none',
    text_color: '#881337',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(190, 18, 60, 0.15)',
    card_text_color: '#881337',
    button_radius: 'rounded-2xl',
    font_family: 'Poppins',
    accent_color: '#BE123C',
    header_layout: 'centered',
  },
  {
    id: 'sun',
    name: 'Sun',
    subtitle: 'Vibrant solar gold & royal cobalt accent',
    background_type: 'gradient',
    background_color: '#FBBF24',
    background_gradient: 'linear-gradient(135deg, #FBBF24 0%, #F59E0B 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.4)',
    card_text_color: '#78350F',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#1D4ED8',
    header_layout: 'centered',
  },
  {
    id: 'flamingo',
    name: 'Flamingo',
    subtitle: 'Playful neon bubblegum & deep magenta',
    background_type: 'gradient',
    background_color: '#F472B6',
    background_gradient: 'linear-gradient(135deg, #F472B6 0%, #EC4899 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.35)',
    card_text_color: '#831843',
    button_radius: 'rounded-2xl',
    font_family: 'Montserrat',
    accent_color: '#BE185D',
    header_layout: 'centered',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    subtitle: 'Provencal purple blossom & clean cards',
    background_type: 'gradient',
    background_color: '#C4B5FD',
    background_gradient: 'linear-gradient(135deg, #C4B5FD 0%, #A78BFA 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.35)',
    card_text_color: '#4C1D95',
    button_radius: 'rounded-2xl',
    font_family: 'Inter',
    accent_color: '#6D28D9',
    header_layout: 'centered',
  },
  {
    id: 'caramel',
    name: 'Caramel',
    subtitle: 'Rich artisan dulce de leche & dark espresso',
    background_type: 'gradient',
    background_color: '#D97706',
    background_gradient: 'linear-gradient(135deg, #D97706 0%, #B45309 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FEF3C7',
    card_border: 'rgba(120, 53, 15, 0.2)',
    card_text_color: '#451A03',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#78350F',
    header_layout: 'centered',
  },
  {
    id: 'olive',
    name: 'Olive',
    subtitle: 'Cold-pressed extra virgin olive oil',
    background_type: 'gradient',
    background_color: '#84CC16',
    background_gradient: 'linear-gradient(135deg, #84CC16 0%, #65A30D 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#ECFCCB',
    card_border: 'rgba(54, 83, 20, 0.2)',
    card_text_color: '#1A2E05',
    button_radius: 'rounded-2xl',
    font_family: 'Outfit',
    accent_color: '#365314',
    header_layout: 'centered',
  },
  {
    id: 'sky',
    name: 'Sky',
    subtitle: 'Limitless azure blue & cloud white cards',
    background_type: 'gradient',
    background_color: '#38BDF8',
    background_gradient: 'linear-gradient(135deg, #38BDF8 0%, #0284C7 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.4)',
    card_text_color: '#082F49',
    button_radius: 'rounded-2xl',
    font_family: 'Public Sans',
    accent_color: '#0369A1',
    header_layout: 'centered',
  },
  {
    id: 'amethyst',
    name: 'Amethyst',
    subtitle: 'Royal crystalline purple & obsidian depth',
    background_type: 'dark',
    background_color: '#3B0764',
    background_gradient: 'linear-gradient(135deg, #3B0764 0%, #1E1B4B 100%)',
    background_effect: 'none',
    text_color: '#FAF5FF',
    card_style: 'glass_double_bezel',
    card_bg: 'rgba(255, 255, 255, 0.12)',
    card_border: 'rgba(255, 255, 255, 0.18)',
    card_text_color: '#FAF5FF',
    button_radius: 'rounded-2xl',
    font_family: 'Geist',
    accent_color: '#C084FC',
    header_layout: 'centered',
  },
  {
    id: 'evergreen',
    name: 'Evergreen',
    subtitle: 'Pacific northwest coniferous emerald',
    background_type: 'dark',
    background_color: '#064E3B',
    background_gradient: 'linear-gradient(135deg, #064E3B 0%, #022C22 100%)',
    background_effect: 'none',
    text_color: '#ECFDF5',
    card_style: 'glass_double_bezel',
    card_bg: 'rgba(255, 255, 255, 0.12)',
    card_border: 'rgba(52, 211, 153, 0.25)',
    card_text_color: '#ECFDF5',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#34D399',
    header_layout: 'centered',
  },
  {
    id: 'wheat',
    name: 'Wheat',
    subtitle: 'Golden harvest prairie & warm bread crust',
    background_type: 'gradient',
    background_color: '#FEF08A',
    background_gradient: 'linear-gradient(135deg, #FEF08A 0%, #FDE047 100%)',
    background_effect: 'none',
    text_color: '#713F12',
    card_style: 'solid_flat',
    card_bg: '#FEF9C3',
    card_border: 'rgba(161, 98, 7, 0.2)',
    card_text_color: '#713F12',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#A16207',
    header_layout: 'centered',
  },
  {
    id: 'moss',
    name: 'Moss',
    subtitle: 'Deep forest floor velvety moss',
    background_type: 'dark',
    background_color: '#4D7C0F',
    background_gradient: 'linear-gradient(135deg, #4D7C0F 0%, #3F6212 100%)',
    background_effect: 'none',
    text_color: '#ECFCCB',
    card_style: 'glass_double_bezel',
    card_bg: 'rgba(255, 255, 255, 0.14)',
    card_border: 'rgba(190, 242, 100, 0.25)',
    card_text_color: '#ECFCCB',
    button_radius: 'rounded-2xl',
    font_family: 'Inter',
    accent_color: '#BEF264',
    header_layout: 'centered',
  },
  {
    id: 'mulberry',
    name: 'Mulberry',
    subtitle: 'Dark berry bramble & vintage velvet',
    background_type: 'dark',
    background_color: '#701A75',
    background_gradient: 'linear-gradient(135deg, #701A75 0%, #4A044E 100%)',
    background_effect: 'none',
    text_color: '#FDF2F8',
    card_style: 'glass_double_bezel',
    card_bg: 'rgba(255, 255, 255, 0.12)',
    card_border: 'rgba(244, 114, 182, 0.25)',
    card_text_color: '#FDF2F8',
    button_radius: 'rounded-2xl',
    font_family: 'Montserrat',
    accent_color: '#F472B6',
    header_layout: 'centered',
  },
  {
    id: 'latte',
    name: 'Latte',
    subtitle: 'Creamy barista oat latte & dark roast',
    background_type: 'gradient',
    background_color: '#F5EBE0',
    background_gradient: 'linear-gradient(135deg, #F5EBE0 0%, #E3D5CA 100%)',
    background_effect: 'none',
    text_color: '#3D2C1D',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(127, 85, 57, 0.15)',
    card_text_color: '#3D2C1D',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#7F5539',
    header_layout: 'centered',
  },
  {
    id: 'violet',
    name: 'Violet',
    subtitle: 'Electric high-voltage ultraviolet',
    background_type: 'gradient',
    background_color: '#8B5CF6',
    background_gradient: 'linear-gradient(135deg, #8B5CF6 0%, #6D28D9 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.4)',
    card_text_color: '#2E1065',
    button_radius: 'rounded-2xl',
    font_family: 'Poppins',
    accent_color: '#4C1D95',
    header_layout: 'centered',
  },
  {
    id: 'coral',
    name: 'Coral',
    subtitle: 'Vibrant Great Barrier Reef living coral',
    background_type: 'gradient',
    background_color: '#FB7185',
    background_gradient: 'linear-gradient(135deg, #FB7185 0%, #E11D48 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.35)',
    card_text_color: '#4C0519',
    button_radius: 'rounded-2xl',
    font_family: 'Manrope',
    accent_color: '#9F1239',
    header_layout: 'centered',
  },
  {
    id: 'magnolia',
    name: 'Magnolia',
    subtitle: 'Southern spring blossom & pale lilac',
    background_type: 'gradient',
    background_color: '#F3E8FF',
    background_gradient: 'linear-gradient(135deg, #F3E8FF 0%, #E9D5FF 100%)',
    background_effect: 'none',
    text_color: '#581C87',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(168, 85, 247, 0.15)',
    card_text_color: '#581C87',
    button_radius: 'rounded-2xl',
    font_family: 'Outfit',
    accent_color: '#A855F7',
    header_layout: 'centered',
  },
  {
    id: 'denim',
    name: 'Denim',
    subtitle: 'Classic vintage indigo selvedge',
    background_type: 'gradient',
    background_color: '#3B82F6',
    background_gradient: 'linear-gradient(135deg, #3B82F6 0%, #1D4ED8 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.35)',
    card_text_color: '#172554',
    button_radius: 'rounded-2xl',
    font_family: 'Public Sans',
    accent_color: '#1E40AF',
    header_layout: 'centered',
  },
  {
    id: 'monolake',
    name: 'Monolake',
    subtitle: 'Volcanic mineral caldera & obsidian soil',
    background_type: 'dark',
    background_color: '#422006',
    background_gradient: 'linear-gradient(135deg, #422006 0%, #292524 100%)',
    background_effect: 'none',
    text_color: '#FEF3C7',
    card_style: 'glass_double_bezel',
    card_bg: 'rgba(255, 255, 255, 0.12)',
    card_border: 'rgba(245, 158, 11, 0.25)',
    card_text_color: '#FEF3C7',
    button_radius: 'rounded-2xl',
    font_family: 'Geist',
    accent_color: '#F59E0B',
    header_layout: 'centered',
  },
  {
    id: 'berry',
    name: 'Berry',
    subtitle: 'Wild dark boysenberry & royal indigo',
    background_type: 'dark',
    background_color: '#831843',
    background_gradient: 'linear-gradient(135deg, #831843 0%, #500724 100%)',
    background_effect: 'none',
    text_color: '#FFE4E6',
    card_style: 'glass_double_bezel',
    card_bg: 'rgba(255, 255, 255, 0.14)',
    card_border: 'rgba(244, 63, 94, 0.25)',
    card_text_color: '#FFE4E6',
    button_radius: 'rounded-2xl',
    font_family: 'Montserrat',
    accent_color: '#F43F5E',
    header_layout: 'centered',
  },
  {
    id: 'mint',
    name: 'Mint',
    subtitle: 'Cool retro spearmint & dark teal punch',
    background_type: 'gradient',
    background_color: '#2DD4BF',
    background_gradient: 'linear-gradient(135deg, #2DD4BF 0%, #0F766E 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: '#FFFFFF',
    card_border: 'rgba(255, 255, 255, 0.4)',
    card_text_color: '#042F2E',
    button_radius: 'rounded-2xl',
    font_family: 'Plus Jakarta Sans',
    accent_color: '#0D9488',
    header_layout: 'centered',
  },
  {
    id: 'crimson',
    name: 'Crimson',
    subtitle: 'Midnight maritime deep cyan & dark navy',
    background_type: 'gradient',
    background_color: '#0284C7',
    background_gradient: 'linear-gradient(135deg, #0284C7 0%, #0369A1 100%)',
    background_effect: 'none',
    text_color: '#FFFFFF',
    card_style: 'solid_flat',
    card_bg: 'rgba(255, 255, 255, 0.95)',
    card_border: 'rgba(255, 255, 255, 0.4)',
    card_text_color: '#082F49',
    button_radius: 'rounded-2xl',
    font_family: 'Inter',
    accent_color: '#0C4A6E',
    header_layout: 'centered',
  },
  {
    id: 'light',
    name: 'Light',
    subtitle: 'Pure stark studio monochrome',
    background_type: 'solid',
    background_color: '#FFFFFF',
    background_gradient: 'linear-gradient(180deg, #FFFFFF 0%, #FAFAFA 100%)',
    background_effect: 'none',
    text_color: '#09090B',
    card_style: 'solid_flat',
    card_bg: '#F4F4F5',
    card_border: 'rgba(0, 0, 0, 0.08)',
    card_text_color: '#09090B',
    button_radius: 'rounded-2xl',
    font_family: 'Geist',
    accent_color: '#18181B',
    header_layout: 'centered',
  },
  {
    id: 'dark',
    name: 'Dark',
    subtitle: 'OLED black & dark glass surfaces',
    background_type: 'dark',
    background_color: '#000000',
    background_gradient: 'linear-gradient(180deg, #000000 0%, #09090B 100%)',
    background_effect: 'none',
    text_color: '#FAFAFA',
    card_style: 'glass_double_bezel',
    card_bg: 'rgba(24, 24, 27, 0.85)',
    card_border: 'rgba(255, 255, 255, 0.12)',
    card_text_color: '#FAFAFA',
    button_radius: 'rounded-2xl',
    font_family: 'Geist',
    accent_color: '#FFFFFF',
    header_layout: 'centered',
  },
];

export const MODERN_THEME_PRESETS = THEME_PRESETS;

export const TACTILE_CARD_STYLES = [
  { id: 'glass_double_bezel', label: 'Double-Bezel Glass (Apple)', description: 'Frosted acrylic glass with dual highlight rim' },
  { id: 'tactile_convex', label: 'Tactile Convex 3D (Pillowed)', description: 'Floats off page with top specular highlight & soft drop shadow' },
  { id: 'tactile_concave', label: 'Tactile Concave Inset (Carved)', description: 'Soft neumorphic inner shadow carved into canvas' },
  { id: 'hard_shadow', label: 'Hard Neobrutalist', description: 'Bold solid border with hard offset physical shadow' },
  { id: 'neon_glow', label: 'Cyber Glow Halo', description: 'Deep dark card with glowing ambient neon outline' },
  { id: 'soft_pill', label: 'Soft Marshmallow Pill', description: 'Rounded pill shape with diffused elevation' },
  { id: 'minimal_outline', label: 'Minimal Architectural Hairline', description: 'Ultra-clean 1px crisp outline' },
  { id: 'solid_flat', label: 'Solid Modern Flat', description: 'High-opacity modern flat surface' },
];

export const BACKGROUND_EFFECTS = [
  { id: 'none', label: 'Clean Canvas', description: 'Solid or gradient backdrop without overlays' },
  { id: 'grain', label: 'Film Grain & Washi Paper', description: 'Subtle SVG noise texture overlay for luxury physical feel' },
  { id: 'ambient_orbs', label: 'Ambient Light Orbs', description: 'Floating defocused glowing light spheres behind cards' },
  { id: 'mesh_glow', label: 'Procedural Liquid Mesh', description: 'Multi-stop fluid color blend with dynamic ambient light' },
];

export const HEADER_LAYOUTS = [
  {
    id: 'centered',
    label: 'Centered',
    description: 'Avatar centered, title and bio centered below',
  },
  {
    id: 'left_stacked',
    label: 'Top-Left Stacked',
    description: 'Avatar top-left, title and bio left-aligned below',
  },
  {
    id: 'left_row',
    label: 'Left Row',
    description: 'Avatar on left side with title and bio inline beside it',
  },
  {
    id: 'right_stacked',
    label: 'Top-Right Stacked',
    description: 'Avatar top-right, title and bio right-aligned below',
  },
  {
    id: 'right_row',
    label: 'Right Row',
    description: 'Avatar on right side with title and bio inline to the left',
  },
];

export const BUTTON_STYLES = [
  { id: 'solid', label: 'Solid', description: 'Filled high-contrast background' },
  { id: 'outline', label: 'Outline', description: 'Transparent background with 1.5px border' },
];

export const BUTTON_SHAPES = [
  { id: 'standard', label: 'Standard', radius: 'rounded-2xl', cornerRadius: 16 },
  { id: 'pill', label: 'Pill', radius: 'rounded-full', cornerRadius: 9999 },
  { id: 'sharp', label: 'Sharp', radius: 'rounded-none', cornerRadius: 0 },
];

export const FONTS_LIST = [
  { id: 'Manrope', label: 'Manrope', sample: 'Modern Sans' },
  { id: 'Inter', label: 'Inter', sample: 'Clean Tech' },
  { id: 'Plus Jakarta Sans', label: 'Plus Jakarta Sans', sample: 'Apple Editorial' },
  { id: 'Montserrat', label: 'Montserrat', sample: 'Geometric Chic' },
  { id: 'Poppins', label: 'Poppins', sample: 'Friendly Curve' },
  { id: 'Public Sans', label: 'Public Sans', sample: 'Architectural' },
  { id: 'Geist', label: 'Geist', sample: 'Minimal Mono' },
  { id: 'Outfit', label: 'Outfit', sample: 'Modern Fashion' },
  { id: 'Playfair Display', label: 'Playfair Display', sample: 'Luxury Serif' },
  { id: 'Space Grotesk', label: 'Space Grotesk', sample: 'Cyber Edge' },
  { id: 'Oswald', label: 'Oswald', sample: 'Bold Punch' },
  { id: 'Barlow', label: 'Barlow', sample: 'Clean Grotesk' },
  { id: 'Kanit', label: 'Kanit', sample: 'Contemporary' },
  { id: 'Rasa', label: 'Rasa', sample: 'Fine Serif' },
  { id: 'Cabin', label: 'Cabin', sample: 'Humanist' },
  { id: 'Asap', label: 'Asap', sample: 'Soft Rounded' },
  { id: 'Rajdhani', label: 'Rajdhani', sample: 'Technical' },
  { id: 'IBM Plex Sans', label: 'IBM Plex Sans', sample: 'Corporate Neutral' },
  { id: 'KoHo', label: 'KoHo', sample: 'Geometric' },
  { id: 'DM Sans', label: 'DM Sans', sample: 'Fluid Editorial' },
  { id: 'Lora', label: 'Lora', sample: 'Classic Literary' },
  { id: 'Roboto', label: 'Roboto', sample: 'Universal Sans' },
];

/**
 * Dynamically injects Google Font link tag into document head
 */
export const loadGoogleFont = (fontFamily) => {
  if (!fontFamily || typeof document === 'undefined') return;
  const cleanFamily = fontFamily.split(',')[0].trim().replace(/['"]/g, '');
  if (['system-ui', 'sans-serif', 'serif', 'monospace'].includes(cleanFamily.toLowerCase())) return;

  const fontId = `google-font-${cleanFamily.toLowerCase().replace(/\s+/g, '-')}`;
  if (document.getElementById(fontId)) return;

  try {
    const link = document.createElement('link');
    link.id = fontId;
    link.rel = 'stylesheet';
    link.href = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(cleanFamily)}:wght@300;400;500;600;700;800&display=swap`;
    document.head.appendChild(link);
  } catch (e) {
    // Non-blocking
  }
};

/**
 * Computes exact inline styles and Tailwind classes for a card or button.
 * Respects fine-tuned slider percentages (corner radius, border width, shadow depth, soft/solid shadow)
 */
export const getTactileCardStyles = (cardStyle, theme = {}, isFeatured = false, blockOverrides = {}) => {
  const isOutlineButton = theme.button_style === 'outline';

  const rawBg = blockOverrides.has_custom_bg
    ? blockOverrides.card_bg
    : (theme.card_bg || blockOverrides.card_bg || 'rgba(255, 255, 255, 0.85)');
  const bg = isOutlineButton ? 'transparent' : rawBg;

  const border = blockOverrides.has_custom_border
    ? blockOverrides.card_border
    : (theme.card_border || blockOverrides.card_border || (isOutlineButton ? (theme.accent_color || 'currentColor') : 'rgba(0, 0, 0, 0.08)'));
  
  const textColor = blockOverrides.has_custom_text_color
    ? blockOverrides.card_text_color
    : (theme.card_text_color || blockOverrides.card_text_color || theme.text_color || '#18181B');
  const accent = theme.accent_color || '#6366F1';

  // Dynamic slider or button shape values
  let cornerPct = theme.card_corner_radius !== undefined ? Number(theme.card_corner_radius) : 16;
  if (theme.button_shape === 'pill') cornerPct = 9999;
  if (theme.button_shape === 'sharp') cornerPct = 0;
  if (theme.button_shape === 'standard') cornerPct = 16;

  const borderPct = theme.card_border_width !== undefined ? Number(theme.card_border_width) : (isOutlineButton ? 1.5 : 0);
  const shadowPct = isOutlineButton ? 0 : (theme.card_shadow_depth !== undefined ? Number(theme.card_shadow_depth) : 100);
  const shadowType = theme.card_shadow_type || 'soft';
  const isTactile = theme.tactile_blocks ?? true;

  let borderRadiusStyle = '16px';
  if (cornerPct >= 40 || cornerPct >= 999) {
    borderRadiusStyle = '9999px';
  } else if (cornerPct === 0) {
    borderRadiusStyle = '0px';
  } else if (cornerPct > 0 && cornerPct <= 39) {
    borderRadiusStyle = `${cornerPct}px`;
  } else {
    borderRadiusStyle = `${Math.round((cornerPct / 100) * 36)}px`;
  }

  let borderWidthStyle = isOutlineButton ? '1.5px' : '1px';
  if (borderPct > 0 && borderPct <= 6) {
    borderWidthStyle = `${borderPct}px`;
  } else if (borderPct > 6) {
    borderWidthStyle = `${((borderPct / 100) * 3).toFixed(1)}px`;
  } else if (borderPct === 0 && !isOutlineButton && !cardStyle?.includes('outline') && !cardStyle?.includes('hard')) {
    borderWidthStyle = '1px';
  }

  let customShadow = '0 4px 12px -2px rgba(0, 0, 0, 0.05)';
  let backdropBlur = isOutlineButton ? '' : 'backdrop-blur-md';
  let extraClasses = '';

  const blurAmount = theme.glass_blur !== undefined ? Number(theme.glass_blur) : (isOutlineButton ? 0 : 16);

  if (shadowPct === 0 || isOutlineButton) {
    customShadow = 'none';
  } else if (shadowType === 'solid') {
    const depth = Math.max(1, Math.round((shadowPct / 100) * 8));
    customShadow = `${depth}px ${depth}px 0px rgba(0, 0, 0, 0.85)`;
  } else {
    const blurDepth = Math.round((shadowPct / 100) * 28);
    const yOffset = Math.round((shadowPct / 100) * 14);
    const opacity = (0.05 + (shadowPct / 100) * 0.15).toFixed(2);

    if (isTactile) {
      switch (cardStyle) {
        case 'tactile_convex':
          customShadow = `inset 0 1px 1px rgba(255, 255, 255, 0.6), 0 ${yOffset}px ${blurDepth}px -4px rgba(0, 0, 0, ${opacity})`;
          break;
        case 'tactile_concave':
          customShadow = `inset 0 2px 6px rgba(0, 0, 0, ${opacity}), inset 0 -1px 2px rgba(255, 255, 255, 0.3)`;
          break;
        case 'neon_glow':
          customShadow = `0 0 ${Math.round((shadowPct / 100) * 24)}px ${accent}45, inset 0 0 10px ${accent}25`;
          break;
        case 'glass_double_bezel':
        case 'glassmorphic':
          customShadow = `inset 0 1px 0 0 rgba(255, 255, 255, 0.4), 0 ${yOffset}px ${blurDepth}px -4px rgba(0, 0, 0, ${opacity})`;
          backdropBlur = 'backdrop-blur-xl';
          break;
        case 'soft_pill':
          customShadow = `0 ${yOffset}px ${blurDepth}px -6px rgba(0, 0, 0, ${opacity})`;
          break;
        default:
          customShadow = `0 ${yOffset}px ${blurDepth}px rgba(0, 0, 0, ${opacity})`;
          break;
      }
    } else {
      customShadow = `0 ${yOffset}px ${blurDepth}px rgba(0, 0, 0, ${opacity})`;
    }
  }

  if (isFeatured || blockOverrides.animation === 'pulse') {
    extraClasses += ' ring-2 ring-amber-400/90 shadow-amber-400/20 animate-pulse-subtle';
  } else if (blockOverrides.animation === 'bounce') {
    extraClasses += ' animate-bounce';
  } else if (blockOverrides.animation === 'wiggle') {
    extraClasses += ' hover:animate-wiggle';
  } else if (blockOverrides.animation === 'glow') {
    extraClasses += ' ring-2 ring-indigo-500/80 shadow-indigo-500/30';
  }

  return {
    style: {
      backgroundColor: bg,
      borderColor: border,
      borderWidth: borderWidthStyle,
      borderStyle: 'solid',
      color: textColor,
      borderRadius: borderRadiusStyle,
      boxShadow: customShadow,
      backdropFilter: blurAmount > 0 ? `blur(${blurAmount}px)` : undefined,
      WebkitBackdropFilter: blurAmount > 0 ? `blur(${blurAmount}px)` : undefined,
    },
    className: `${backdropBlur} ${extraClasses}`,
  };
};

export const getProfileAvatarStyles = (theme = {}) => {
  const sizePct = theme.profile_picture_size !== undefined ? Number(theme.profile_picture_size) : 50;
  const shadowPct = theme.profile_picture_shadow !== undefined ? Number(theme.profile_picture_shadow) : 0;
  const borderPct = theme.profile_picture_border !== undefined ? Number(theme.profile_picture_border) : 0;

  const sizePx = sizePct >= 48 ? sizePct : Math.round(52 + (sizePct / 100) * 72);
  const borderWidthPx = Math.round((borderPct / 100) * 6);
  const shadowBlur = Math.round((shadowPct / 100) * 24);
  const shadowOpacity = (0.1 + (shadowPct / 100) * 0.25).toFixed(2);

  return {
    width: `${sizePx}px`,
    height: `${sizePx}px`,
    borderWidth: borderWidthPx > 0 ? `${borderWidthPx}px` : undefined,
    borderColor: borderWidthPx > 0 ? (theme.card_border || 'rgba(255,255,255,0.8)') : undefined,
    borderStyle: borderWidthPx > 0 ? 'solid' : undefined,
    boxShadow: shadowPct > 0 ? `0 8px ${shadowBlur}px rgba(0,0,0,${shadowOpacity})` : undefined,
  };
};

export const getBlockSpacingPx = (theme = {}) => {
  const spacingPct = theme.card_spacing !== undefined ? Number(theme.card_spacing) : 33;
  return Math.round(6 + (spacingPct / 100) * 20);
};

export const getSocialIconSizePx = (theme = {}) => {
  const sizePct = theme.social_icon_size !== undefined ? Number(theme.social_icon_size) : 0;
  return Math.round(18 + (sizePct / 100) * 14);
};
